### Standard Imports for this Dataset

In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
import plotly.express as px

In [2]:
# change display settings to show all dataframe columns as well as complete cell values (no truncating values)
# https://stackoverflow.com/questions/47022070/display-all-dataframe-columns-in-a-jupyter-python-notebook
pd.set_option('display.max_columns', None)

# https://stackoverflow.com/a/51540918
# pd.set_option('display.max_rows', 500)
# pd.set_option('display.width', 1000)
pd.set_option('display.expand_frame_repr', False)
pd.set_option('max_colwidth', None)

## Read Data

In [4]:
#!ls ../data/notable_people_cross-verified/

In [6]:
#read file using utf-8 encoding to accommodate "ä", "ö", ... , "ß" etc.

iso_3 = pd.read_csv("../data/notable_people_cross-verified/wiki_notable_people_cleaned_iso.csv", 
                    encoding='utf-8', index_col=0)

In [ ]:
# info: renamed column containing iso codes in the end 
# to clarify that it is being used for plotting purposes only
# in some results it might still display with the old name as I did not re-run every cell

iso_3.rename(columns={"citizenship_iso3" : "map_iso3"}, inplace=True)

In [13]:
iso_3.sample()

                birth  death  gender      occup_l1              name      un_subregion                    bigperiod_birth                    bigperiod_death    curid      occup_l2 occup_l3  avg_no_readers_2015_2018  non_missing_score  total_count_words  no_wiki_editions  no_external_links  notability_index_sum  notability_index_ranking citizenship un_region group_wikipedia_editions  birth_place_lon  death_place_lon  birth_place_lat  death_place_lat                                      occup_l3_all map_iso3
wikidata_code
Q4951212       1961.0    NaN  Female  Sports/Games  Kathy Guadagnino  Northern America  5.Contemporary period 1901-2020AD  5.Contemporary period 1901-2020AD  5027821  Sports/Games     golf                      3487                  3               3617                 2                  1             18.143379                  937254.0          US   America                      grA        -73.76667              NaN        42.650002              NaN  D:_golf_P:_golf_baker_English_golf_sport_Swedish      USA

In [11]:
# check for how many rows iso3 code is NULL

In [12]:
iso_3["map_iso3"].isnull().sum()

53499

In [16]:
# check sample of data where iso3 code is NULL ranked by notability index

(iso_3.loc[iso_3["map_iso3"].isnull() == True]).sort_values(by="notability_index_ranking").head()

# for some individuals from ancient history it is difficult to assign a specific citizenship based on today's countries

               birth  death gender    occup_l1                   name un_subregion                 bigperiod_birth                 bigperiod_death    curid   occup_l2  occup_l3  avg_no_readers_2015_2018  non_missing_score  total_count_words  no_wiki_editions  no_external_links  notability_index_sum  notability_index_ranking citizenship un_region group_wikipedia_editions  birth_place_lon  death_place_lon  birth_place_lat  death_place_lat                                                                                                                                                                                                                                                                   occup_l3_all map_iso3
wikidata_code
Q302            -4.0   30.0   Male  Leadership                  Jesus          NaN  1.Ancient History Before 500AD  1.Ancient History Before 500AD  1095706  Religious  preacher                  40150488                  3             212421               245                 48             39.171627                     204.5         NaN       NaN                      grA        35.206112        35.229443        31.704445        31.778610  D:_preacher_prophet_carpenter_rabbi_religious_P:_preacher_religious_christianity_English_jésus_seigneur_fils_French_predicatore_figlio_gesù_Italian_ sohn_jesus_German_jesús_académic_predicador_Spanish_pregador_governador_académico_Portuguese_predikant_bibel_son_Swedish      NaN
Q8413          274.0  337.0   Male  Leadership  Constantine the Great          NaN  1.Ancient History Before 500AD  1.Ancient History Before 500AD     7236   Nobility   emperor                  10322065                  3             122124               117                 43             36.417469                     504.0         NaN       NaN                      grA        21.896111        29.917500        43.319168        40.762501                                                       D:_politician_militar_P:_emperor_son_army_English_empereur_règne_French_imperatore_esercito_religiosa_Italian_herrscher_German_comedia_emperador_iglesia_Spanish_imperador_governo_Portuguese_komedi_kejsare_son_Swedish      NaN
Q43600          -1.0   74.0   Male  Leadership    Matthew the Apostle          NaN  1.Ancient History Before 500AD  1.Ancient History Before 500AD    20672  Religious     jesus                   3612053                  3              40185                78                 18             33.014950                    8386.0         NaN       NaN                      grA        35.000000        40.000000        31.000000         9.000000                                       D:_collector_priest_P:_jesus_disciples_bible_English_jésus_French_ gesù_figlio_Italian_apostel_entscheidung_evangelist_German_evangelista_apóstol_jesús_Spanish_convidado_jesus_apóstolo_Portuguese_ författare_författare_bibel_Swedish      NaN
Q172168        250.0  311.0   Male  Leadership               Galerius          NaN  1.Ancient History Before 500AD  1.Ancient History Before 500AD    74631   Nobility   emperor                    669359                  3              50255                57                 21             31.390453                    8834.0         NaN       NaN                      grA        22.174999        23.322001        43.909199        42.698002                                                                                                             D:_politician_P:_emperor_campaign_opponent_English_empereur_French_imperatore_Italian_emperador_reina_campaña_Spanish_imperador_governo_Portuguese_kejsare_Swedish      NaN
Q46768         240.0  310.0   Male  Leadership               Maximian          NaN  1.Ancient History Before 500AD  1.Ancient History Before 500AD    75088   Nobility   emperor                    719525                  3              73092                57                 19             31.742016                    9752.0         NaN       NaN                      grA        19.610556         5.376389        44.966110        43.296665                                                             D:_politician_P:_emperor_political_militar_English_empereur_politique_force_French_imperatore_Italian_ kaiser_German_emperador_político_creador_Spanish_imperador_inteligência_política_Portuguese_kejsare_Swedish      NaN

### Create a List of unique ISO3 Codes present in the Data

In [ ]:
iso_3_unique = iso_3["map_iso3"].unique().tolist()

In [8]:
iso_3_unique

['DEU',
 'CZE',
 'USA',
 'AUT',
 'POL',
 'RUS',
 'UKR',
 'BEL',
 'ITA',
 'FRA',
 'NOR',
 'PHL',
 'BRA',
 'IRL',
 'CMR',
 'IRN',
 'HUN',
 'CHN',
 'GBR',
 'CAN',
 nan,
 'JPN',
 "['AUT', 'HUN']",
 'CHE',
 'VEN',
 'ECU',
 'PRT',
 'NLD',
 'GRC',
 'IND',
 'BGR',
 'EGY',
 'ARG',
 'ROU',
 'COL',
 'TUV',
 'SRB',
 'CHL',
 'KOR',
 'IDN',
 'HRV',
 'FIN',
 'VNM',
 'Roman Empire',
 'KWT',
 'SGP',
 'ESP',
 'COG',
 'DNK',
 'MYS',
 'DMA',
 'NGA',
 'TUN',
 'TUR',
 'LAO',
 'MEX',
 'AUS',
 'PRY',
 'SWE',
 'ZWE',
 'HND',
 'GRD',
 'SVN',
 'PAK',
 'GEO',
 'KAZ',
 'VUT',
 'GHA',
 'NZL',
 'SYR',
 'Holy Roman Empire',
 'Serbia and Montenegro',
 'JAM',
 'BLR',
 'MNE',
 'HKG',
 'TWN',
 'ZAF',
 'THA',
 'XKX',
 'ALB',
 'MNG',
 'FJI',
 'MLT',
 'CUB',
 'ISL',
 'LBR',
 'COM',
 'AZE',
 'GNB',
 'PER',
 'CPV',
 'AGO',
 'BOL',
 'UGA',
 'SVK',
 'LVA',
 'MCO',
 'URY',
 'BRN',
 'BWA',
 'ARM',
 'BEN',
 'MOZ',
 'LTU',
 'AND',
 'SLV',
 'EST',
 'KEN',
 'LBN',
 'BIH',
 'ARE',
 'ETH',
 'Yugoslavia',
 'SUR',
 'ISR',
 'IRQ',
 'MMR',
 'LUX',
 'MAR',
 'UZB',
 'MDA',
 'GIN',
 'TLS',
 'SEN',
 'CYP',
 'MKD',
 'CIV',
 'MUS',
 'LBY',
 'AFG',
 'JOR',
 'Korean Peninsula',
 'LKA',
 'PSE',
 'Tibet',
 'GTM',
 'ZMB',
 'MWI',
 'MDV',
 'GAB',
 'TKM',
 'LIE',
 'NER',
 'OMN',
 'SLE',
 'SAU',
 'VAT',
 'NIC',
 'CRI',
 'DZA',
 'Overseas Territories of US',
 'BLZ',
 'TTO',
 'MDG',
 'BDI',
 'PAN',
 'BHR',
 'KGZ',
 'BFA',
 'TGO',
 'SWZ',
 'YEM',
 'GUY',
 'HTI',
 'PNG',
 'VCT',
 'TCD',
 'ERI',
 'MLI',
 'QAT',
 'TZA',
 'KNA',
 'SYC',
 'CAF',
 'ATG',
 'RWA',
 'BGD',
 'WSM',
 'GMB',
 'DJI',
 'SDN',
 'LCA',
 'BRB',
 'KHM',
 'STP',
 'SOM',
 'BTN',
 'NPL',
 'TJK',
 'NAM',
 'PRK',
 'Scotland',
 'SMR',
 'DOM',
 'TON',
 'MRT',
 'BHS',
 'SLB',
 'GNQ',
 'KIR',
 'MHL',
 'LSO',
 'PLW',
 'FSM',
 'NRU',
 'Kurdistan',
 "['DNK', 'NOR']",
 'Babylon',
 'Judea',
 'Transnistria',
 'SSD',
 'England',
 'Wales',
 'Pre-Columbian era',
 'British North America',
 'MAC',
 'Abkhazia',
 'Zanzibar',
 'ESH',
 'British Empire',
 'Urartu',
 'Nagorno-Karabakh Republic']

In [9]:
# check and remove "nan" value

type(iso_3_unique[20])

float

In [10]:
iso_3_unique[20]

nan

In [11]:
len(iso_3_unique)

223

In [12]:
iso_3_unique[20] = str(iso_3_unique[20])

In [13]:
type(iso_3_unique[20])

str

In [14]:
iso_3_unique[20]

'nan'

In [15]:
iso_3_unique.remove('nan')

In [16]:
iso_3_unique

['DEU',
 'CZE',
 'USA',
 'AUT',
 'POL',
 'RUS',
 'UKR',
 'BEL',
 'ITA',
 'FRA',
 'NOR',
 'PHL',
 'BRA',
 'IRL',
 'CMR',
 'IRN',
 'HUN',
 'CHN',
 'GBR',
 'CAN',
 'JPN',
 "['AUT', 'HUN']",
 'CHE',
 'VEN',
 'ECU',
 'PRT',
 'NLD',
 'GRC',
 'IND',
 'BGR',
 'EGY',
 'ARG',
 'ROU',
 'COL',
 'TUV',
 'SRB',
 'CHL',
 'KOR',
 'IDN',
 'HRV',
 'FIN',
 'VNM',
 'Roman Empire',
 'KWT',
 'SGP',
 'ESP',
 'COG',
 'DNK',
 'MYS',
 'DMA',
 'NGA',
 'TUN',
 'TUR',
 'LAO',
 'MEX',
 'AUS',
 'PRY',
 'SWE',
 'ZWE',
 'HND',
 'GRD',
 'SVN',
 'PAK',
 'GEO',
 'KAZ',
 'VUT',
 'GHA',
 'NZL',
 'SYR',
 'Holy Roman Empire',
 'Serbia and Montenegro',
 'JAM',
 'BLR',
 'MNE',
 'HKG',
 'TWN',
 'ZAF',
 'THA',
 'XKX',
 'ALB',
 'MNG',
 'FJI',
 'MLT',
 'CUB',
 'ISL',
 'LBR',
 'COM',
 'AZE',
 'GNB',
 'PER',
 'CPV',
 'AGO',
 'BOL',
 'UGA',
 'SVK',
 'LVA',
 'MCO',
 'URY',
 'BRN',
 'BWA',
 'ARM',
 'BEN',
 'MOZ',
 'LTU',
 'AND',
 'SLV',
 'EST',
 'KEN',
 'LBN',
 'BIH',
 'ARE',
 'ETH',
 'Yugoslavia',
 'SUR',
 'ISR',
 'IRQ',
 'MMR',
 'LUX',
 'MAR',
 'UZB',
 'MDA',
 'GIN',
 'TLS',
 'SEN',
 'CYP',
 'MKD',
 'CIV',
 'MUS',
 'LBY',
 'AFG',
 'JOR',
 'Korean Peninsula',
 'LKA',
 'PSE',
 'Tibet',
 'GTM',
 'ZMB',
 'MWI',
 'MDV',
 'GAB',
 'TKM',
 'LIE',
 'NER',
 'OMN',
 'SLE',
 'SAU',
 'VAT',
 'NIC',
 'CRI',
 'DZA',
 'Overseas Territories of US',
 'BLZ',
 'TTO',
 'MDG',
 'BDI',
 'PAN',
 'BHR',
 'KGZ',
 'BFA',
 'TGO',
 'SWZ',
 'YEM',
 'GUY',
 'HTI',
 'PNG',
 'VCT',
 'TCD',
 'ERI',
 'MLI',
 'QAT',
 'TZA',
 'KNA',
 'SYC',
 'CAF',
 'ATG',
 'RWA',
 'BGD',
 'WSM',
 'GMB',
 'DJI',
 'SDN',
 'LCA',
 'BRB',
 'KHM',
 'STP',
 'SOM',
 'BTN',
 'NPL',
 'TJK',
 'NAM',
 'PRK',
 'Scotland',
 'SMR',
 'DOM',
 'TON',
 'MRT',
 'BHS',
 'SLB',
 'GNQ',
 'KIR',
 'MHL',
 'LSO',
 'PLW',
 'FSM',
 'NRU',
 'Kurdistan',
 "['DNK', 'NOR']",
 'Babylon',
 'Judea',
 'Transnistria',
 'SSD',
 'England',
 'Wales',
 'Pre-Columbian era',
 'British North America',
 'MAC',
 'Abkhazia',
 'Zanzibar',
 'ESH',
 'British Empire',
 'Urartu',
 'Nagorno-Karabakh Republic']

In [17]:
# identify all values that do not correspond to necessary ISO3 format
# i.e. where no unique ISO3 code could be found by country converter

non_iso_3 = []

for c in range(len(iso_3_unique)):
    if len(iso_3_unique[c]) != 3:
        non_iso_3.append(iso_3_unique[c])
    else:
        print(c)

0
1
2
3
4
5
6
7
8
9
10
11
12
13
14
15
16
17
18
19
20
22
23
24
25
26
27
28
29
30
31
32
33
34
35
36
37
38
39
40
41
43
44
45
46
47
48
49
50
51
52
53
54
55
56
57
58
59
60
61
62
63
64
65
66
67
68
71
72
73
74
75
76
77
78
79
80
81
82
83
84
85
86
87
88
89
90
91
92
93
94
95
96
97
98
99
100
101
102
103
104
105
106
107
108
109
110
111
113
114
115
116
117
118
119
120
121
122
123
124
125
126
127
128
129
130
132
133
135
136
137
138
139
140
141
142
143
144
145
146
147
148
149
151
152
153
154
155
156
157
158
159
160
161
162
163
164
165
166
167
168
169
170
171
172
173
174
175
176
177
178
179
180
181
182
183
184
185
186
187
188
189
190
192
193
194
195
196
197
198
199
200
201
202
203
204
210
215
218

In [18]:
#non_iso_3

In [19]:
iso_3["citizenship"].unique()

array(['Germany', 'Czech Republic', 'US', 'Austria', 'Poland', 'Russia',
       'Ukraine', 'Belgium', 'Italy', 'France', 'Norway', 'Philippines',
       'Brazil', 'Ireland', 'Cameroon', 'Iran', 'Hungary', 'China',
       'United Kingdom', 'Canada', nan, 'Japan', 'Austria-Hungary',
       'Switzerland', 'Venezuela', 'Ecuador', 'Portugal', 'Netherlands',
       'Greece', 'India', 'Bulgaria', 'Egypt', 'Argentina', 'Romania',
       'Colombia', 'Tuvalu', 'Serbia', 'Chile', 'South Korea',
       'Indonesia', 'Croatia', 'Finland', 'Vietnam', 'Roman Empire',
       'Kuwait', 'Singapore', 'Spain', 'Congo', 'Denmark', 'Malaysia',
       'Dominica', 'Nigeria', 'Tunisia', 'Turkey', 'Laos', 'Mexico',
       'Australia', 'Paraguay', 'Sweden', 'Zimbabwe', 'Honduras',
       'Grenada', 'Slovenia', 'Pakistan', 'Georgia', 'Kazakhstan',
       'Vanuatu', 'Ghana', 'New Zealand', 'Syria', 'Holy Roman Empire',
       'Serbia and Montenegro', 'Jamaica', 'Belarus', 'Montenegro',
       'Hong Kong', 'Taiwan', 'South Africa', 'Thailand', 'Kosovo',
       'Albania', 'Mongolia', 'Fiji', 'Malta', 'Cuba', 'Iceland',
       'Liberia', 'Czechoslovakia', 'Comoros', 'Azerbaijan',
       'Guinea-Bissau', 'Peru', 'Cape Verde', 'Angola', 'Bolivia',
       'Uganda', 'Slovakia', 'Latvia', 'Monaco', 'Uruguay', 'Brunei',
       'Botswana', 'Armenia', 'Benin', 'Mozambique', 'Lithuania',
       'Andorra', 'El Salvador', 'Estonia', 'Kenya', 'Lebanon',
       'Bosnia and Herzegovina', 'United Arab Emirates', 'Ethiopia',
       'Yugoslavia', 'Suriname', 'Israel', 'Iraq', 'Myanmar',
       'Luxembourg', 'Morocco', 'Uzbekistan', 'Moldova', 'Guinea',
       'East Timor', 'Senegal', 'Cyprus', 'Macedonia', 'Ivory Coast',
       'Mauritius', 'Libya', 'Afghanistan', 'Jordan', 'Korean Peninsula',
       'Sri Lanka', 'Palestine', 'Tibet', 'Guatemala', 'Zambia', 'Malawi',
       'Maldives', 'Gabon', 'Northern Cyprus', 'Turkmenistan',
       'Liechtenstein', 'Niger', 'Oman', 'Sierra Leone', 'Saudi Arabia',
       'Vatican City', 'Nicaragua', 'Costa Rica', 'Algeria',
       'Overseas Territories of US', 'Belize', 'Trinidad and Tobago',
       'Madagascar', 'Burundi', 'Panama', 'Bahrain', 'Kyrgyzstan',
       'Burkina Faso', 'Togo', 'Swaziland', 'Yemen', 'Guyana', 'Haiti',
       'Papua New Guinea', 'Saint Vincent and the Grenadines',
       'Overseas Territories of United Kingdom', 'Chad', 'Eritrea',
       'Mali', 'Qatar', 'Tanzania', 'Saint Kitts and Nevis', 'Seychelles',
       'Central African Republic', 'Antigua and Barbuda', 'Rwanda',
       'Bangladesh', 'Samoa', 'Gambia', 'Djibouti', 'Sudan',
       'Saint Lucia', 'Barbados', 'Cambodia', 'São Tomé and Príncipe',
       'Somalia', 'Bhutan', 'Nepal', 'Tajikistan', 'Namibia',
       'North Korea', 'Scotland', 'San Marino', 'Dominican republic',
       'Tonga', 'Mauritania', 'The Bahamas', 'Solomon Islands',
       'Equatorial Guinea', 'Kiribati', 'Assyria', 'Marshall Islands',
       'Lesotho', 'Palau', 'Overseas Territories of New Zealand',
       'Polishâ\x80\x93Lithuanian Commonwealth',
       'Polish–Lithuanian Commonwealth', 'Federated States of Micronesia',
       'Nauru', 'Kurdistan', 'Denmark-Norway', 'Babylon', 'Judea',
       'Transnistria', 'South Sudan', 'England', 'Wales',
       'Pre-Columbian era', 'British North America', 'Dominican Republic',
       'Macau', 'Abkhazia', 'Overseas Territories of Netherlands',
       'Zanzibar', 'Western Sahara', 'Overseas Territories of France',
       'British Empire', 'Urartu', 'Nagorno-Karabakh Republic',
       'Overseas Territories of Australia'], dtype=object)

In [20]:
iso_3.loc[iso_3["citizenship"] == "Austria-Hungary"].head()

     wikidata_code   birth   death  gender           occup_l1             name    un_subregion                  bigperiod_birth                    bigperiod_death     curid                 occup_l2    occup_l3  avg_no_readers_2015_2018  non_missing_score  total_count_words  no_wiki_editions  no_external_links  notability_index_sum  notability_index_ranking      citizenship un_region group_wikipedia_editions  birth_place_lon  death_place_lon  birth_place_lat  death_place_lat                                                                                        occup_l3_all citizenship_iso3
102       Q1000596  1890.0  1957.0  Female            Culture   Noémi Ferenczy  Western Europe  4.Mid Modern Period 1751-1900AD  5.Contemporary period 1901-2020AD   8536946             Culture-core     painter                      7939                  3               1971                 3                 16             20.786358                  441505.0  Austria-Hungary    Europe                      grB        19.072500        19.040833        47.673332        47.498333                                                                              D:_painter_academic_P:   ['AUT', 'HUN']
160       Q1000929  1764.0  1847.0    Male  Discovery/Science   Imre Festetics  Western Europe  4.Mid Modern Period 1751-1900AD    4.Mid Modern Period 1751-1900AD  41757615                 Academia  geneticist                      7570                  3               1637                 4                  1             18.636293                  922748.0  Austria-Hungary    Europe                      grA        16.850000        16.551945        47.416668        47.381668                                                                  D:_geneticist_P:_ ultimate_English   ['AUT', 'HUN']
310       Q1002064  1856.0  1947.0    Male              Other    János Fliszár  Western Europe  4.Mid Modern Period 1751-1900AD  5.Contemporary period 1901-2020AD  19827873  Worker/Business (small)  translator                      1568                  3               1985                 3                  3             17.726570                  843353.5  Austria-Hungary    Europe                      grA        16.137777        16.161945        46.726112        46.658611                                  D:_journalist_teacher_translator_P:_translator_poet_writer_English   ['AUT', 'HUN']
533       Q1003622  1893.0  1966.0    Male         Leadership     Franz Lahner  Western Europe  4.Mid Modern Period 1751-1900AD  5.Contemporary period 1901-2020AD  24400193                 Military  flying_ace                      1586                  3               3158                 4                  1             17.732084                  977478.0  Austria-Hungary    Europe                      grA        13.616667        14.283334        47.641666        48.299999     D:_flying_ace_P:_world war_flying ace_world war_English_aviatore_pilota_guerra mondiale_Italian   ['AUT', 'HUN']
1422      Q1010497  1875.0  1916.0    Male       Sports/Games  Ferenc Gillemot  Western Europe  4.Mid Modern Period 1751-1900AD  5.Contemporary period 1901-2020AD   8811833             Sports/Games    football                      5806                  3               2344                 3                  1             18.506819                  868090.0  Austria-Hungary    Europe                      grB        19.040833        23.373333        47.498333        45.412224  D:_football_journalist_football_football_sport_runner_swimmer_P:_ sport_football_entraîneur_French   ['AUT', 'HUN']

## Impute selected ISO3 values into non-ISO3 values for Plotting-purposes only

#### Citizenship = "Austria-Hungary"

In [21]:
iso_3["map_iso3"] = iso_3["map_iso3"].str.replace("\['AUT', 'HUN'\]", "AUT")

/var/folders/lb/7nh14nb129d59jc654lkpdlm0000gp/T/ipykernel_58108/2967320854.py:1: FutureWarning: The default value of regex will change from True to False in a future version.
  iso_3["citizenship_iso3"] = iso_3["citizenship_iso3"].str.replace("\['AUT', 'HUN'\]", "AUT")

In [22]:
iso_3.loc[iso_3["citizenship"] == "Austria-Hungary"].head()

     wikidata_code   birth   death  gender           occup_l1             name    un_subregion                  bigperiod_birth                    bigperiod_death     curid                 occup_l2    occup_l3  avg_no_readers_2015_2018  non_missing_score  total_count_words  no_wiki_editions  no_external_links  notability_index_sum  notability_index_ranking      citizenship un_region group_wikipedia_editions  birth_place_lon  death_place_lon  birth_place_lat  death_place_lat                                                                                        occup_l3_all citizenship_iso3
102       Q1000596  1890.0  1957.0  Female            Culture   Noémi Ferenczy  Western Europe  4.Mid Modern Period 1751-1900AD  5.Contemporary period 1901-2020AD   8536946             Culture-core     painter                      7939                  3               1971                 3                 16             20.786358                  441505.0  Austria-Hungary    Europe                      grB        19.072500        19.040833        47.673332        47.498333                                                                              D:_painter_academic_P:              AUT
160       Q1000929  1764.0  1847.0    Male  Discovery/Science   Imre Festetics  Western Europe  4.Mid Modern Period 1751-1900AD    4.Mid Modern Period 1751-1900AD  41757615                 Academia  geneticist                      7570                  3               1637                 4                  1             18.636293                  922748.0  Austria-Hungary    Europe                      grA        16.850000        16.551945        47.416668        47.381668                                                                  D:_geneticist_P:_ ultimate_English              AUT
310       Q1002064  1856.0  1947.0    Male              Other    János Fliszár  Western Europe  4.Mid Modern Period 1751-1900AD  5.Contemporary period 1901-2020AD  19827873  Worker/Business (small)  translator                      1568                  3               1985                 3                  3             17.726570                  843353.5  Austria-Hungary    Europe                      grA        16.137777        16.161945        46.726112        46.658611                                  D:_journalist_teacher_translator_P:_translator_poet_writer_English              AUT
533       Q1003622  1893.0  1966.0    Male         Leadership     Franz Lahner  Western Europe  4.Mid Modern Period 1751-1900AD  5.Contemporary period 1901-2020AD  24400193                 Military  flying_ace                      1586                  3               3158                 4                  1             17.732084                  977478.0  Austria-Hungary    Europe                      grA        13.616667        14.283334        47.641666        48.299999     D:_flying_ace_P:_world war_flying ace_world war_English_aviatore_pilota_guerra mondiale_Italian              AUT
1422      Q1010497  1875.0  1916.0    Male       Sports/Games  Ferenc Gillemot  Western Europe  4.Mid Modern Period 1751-1900AD  5.Contemporary period 1901-2020AD   8811833             Sports/Games    football                      5806                  3               2344                 3                  1             18.506819                  868090.0  Austria-Hungary    Europe                      grB        19.040833        23.373333        47.498333        45.412224  D:_football_journalist_football_football_sport_runner_swimmer_P:_ sport_football_entraîneur_French              AUT

#### Citizenship = "Roman Empire"

["Roman Empire, the ancient empire, centred on the city of Rome"](https://www.britannica.com/place/Roman-Empire)
> Italy/ITA as iso3

In [23]:
iso_3["map_iso3"] = iso_3["map_iso3"].str.replace("Roman Empire", "ITA")

In [24]:
iso_3.loc[iso_3["citizenship"] == "Roman Empire"].head()

     wikidata_code  birth  death  gender    occup_l1                       name     un_subregion                 bigperiod_birth                 bigperiod_death     curid   occup_l2 occup_l3  avg_no_readers_2015_2018  non_missing_score  total_count_words  no_wiki_editions  no_external_links  notability_index_sum  notability_index_ranking   citizenship un_region group_wikipedia_editions  birth_place_lon  death_place_lon  birth_place_lat  death_place_lat                                                                                                                                                                                                            occup_l3_all citizenship_iso3
298       Q1001933  326.0  360.0  Female  Leadership                     Helena  Southern Europe  1.Ancient History Before 500AD  1.Ancient History Before 500AD  18962157   Nobility  empress                     42582                  3              21640                13                  2             24.379295                  301734.0  Roman Empire    Europe                      grA              NaN         4.874722              NaN        45.525555  D:_P:_empress_marriage_emperor_English_épouse_empereur_French_figlia_imperatore_Italian_tochter_kaiser_German_emperatriz_esposa_esposa_Spanish_imperatriz_atriz_consorte_Portuguese_kejsarinna_gift med_dotter_Swedish              ITA
300       Q1001947  350.0    NaN    Male  Leadership  Flavius Mallius Theodorus  Southern Europe  1.Ancient History Before 500AD  1.Ancient History Before 500AD  27977320   Politics   consul                      6355                  3              11388                12                  8             22.860203                  229907.0  Roman Empire    Europe                      grA         9.185321              NaN        45.462906              NaN                                             D:_writer_politician_militar_P:_consul_author_philosophy_English_ consul_French_ scrittore_grammatico_Italian_ schriftsteller_politiker_German_oficial_imperador_Portuguese              ITA
1665       Q101280    NaN  175.0    Male  Leadership                 Pope Soter  Southern Europe  1.Ancient History Before 500AD  1.Ancient History Before 500AD     43248  Religious   priest                    271833                  3              30206                71                 10             29.503347                   40781.0  Roman Empire    Europe                      grA        13.416667        12.482778        41.349998        41.893055                                                                D:_priest_P:_bishop_marriage_priest_English_vescovo_papa_chiesa_Italian_bischof_German_ papa_iglesia_Spanish_papa_igreja_Portuguese_ påve_helgon_Swedish              ITA
1690       Q101306    NaN  217.0    Male  Leadership            Pope Zephyrinus  Southern Europe  1.Ancient History Before 500AD  1.Ancient History Before 500AD     49802  Religious   priest                    306068                  3              31913                71                 11             29.763948                   33920.0  Roman Empire    Europe                      grA        12.482778        12.482778        41.893055        41.893055                                               D:_priest_P:_bishop_pope_advisor_English_prêtre_French_vescovo_papa_chiesa_Italian_bischof_German_ papa_iglesia_Spanish_papa_igreja_Portuguese_ påve_helgon_kyrka_Swedish              ITA
2775       Q102131  255.0  309.0    Male  Leadership           Pope Marcellus I  Southern Europe  1.Ancient History Before 500AD  1.Ancient History Before 500AD     23958  Religious   priest                    248083                  3              36079                65                 13             29.743740                   27224.0  Roman Empire    Europe                      grA        12.482778        12.482778        41.893055        41.893055                                                                D:_priest_P:_bishop_pope_bishop_English_ pape_French_vescovo_papa_chiesa_Italian_bischof_German_martir_papa_igreja_Portuguese_ påve_helgon_kyrka_Swedish              ITA

#### Citizenship = "Holy Roman Empire"

> Austria/AUT as approx. center

In [25]:
iso_3["map_iso3"] = iso_3["map_iso3"].str.replace("Holy Roman Empire", "AUT")

In [26]:
iso_3["map_iso3"] = iso_3["map_iso3"].str.replace("Holy ITA", "AUT")

In [27]:
iso_3.loc[iso_3["citizenship"] == "Holy Roman Empire"].head()

      wikidata_code   birth   death gender           occup_l1                                               name    un_subregion                      bigperiod_birth                    bigperiod_death     curid      occup_l2    occup_l3  avg_no_readers_2015_2018  non_missing_score  total_count_words  no_wiki_editions  no_external_links  notability_index_sum  notability_index_ranking        citizenship un_region group_wikipedia_editions  birth_place_lon  death_place_lon  birth_place_lat  death_place_lat                                                                                                                                                                     occup_l3_all citizenship_iso3
1296        Q100979  1632.0  1705.0   Male  Discovery/Science                                    Johann Schilter  Western Europe    3.Early Modern Period 1501-1750AD  3.Early Modern Period 1501-1750AD   1182669      Academia   historian                      1836                  3               4369                 2                 16             19.831865                  545563.0  Holy Roman Empire    Europe                      grB        12.250000         7.752222        51.166668        48.573334                                                                                          D:_historian_P:_jurisconsulte_historien_French_rechtsgelehrter_gelehrte_forscher_German              AUT
9415       Q1029893  1787.0  1864.0   Male         Leadership  Carlo Emmanuele dal Pozzo, 5th Prince of Cisterna  Western Europe      4.Mid Modern Period 1751-1900AD    4.Mid Modern Period 1751-1900AD  26162367      Nobility       noble                     16504                  3              13910                 6                  3             22.584240                  313994.0  Holy Roman Empire    Europe                      grA         7.700000         7.700000        45.066666        45.066666                                                  D:_politician_P:_noble_politician_noble_English_noble_politique_royaume_French_patriota_Italian_príncipe_noble_político_Spanish              AUT
9616        Q103024  1490.0  1547.0   Male            Culture                                        Johann Horn  Western Europe  2.Post-Classical History 501-1500AD  3.Early Modern Period 1501-1750AD   1405393  Culture-core      writer                      2578                  3               1979                 2                  9             18.848370                  673583.0  Holy Roman Empire    Europe                      grB        12.929798        14.906389        49.440605        50.412498                                                                                                                               D:_writer_poet_theologian_P:_bischof_gesang_German              AUT
27244      Q1041849  1777.0  1863.0   Male         Leadership                                    Carlo Armellini  Western Europe      4.Mid Modern Period 1751-1900AD    4.Mid Modern Period 1751-1900AD   7269158      Politics  politician                     21245                  3               9973                 9                 12             24.039337                  127403.0  Holy Roman Empire    Europe                      grA        12.482778         4.369167        41.893055        50.850834  D:_jurist_politician_P:_politician_activist_jurist_English_juriste_politique_French_giurista_politico_Italian_politiker_jurist_German_abogad_político_Spanish_politiker_Swedish              AUT
27483      Q1042264  1805.0  1879.0   Male         Leadership                              Carlo Luigi Morichini  Western Europe      4.Mid Modern Period 1751-1900AD    4.Mid Modern Period 1751-1900AD  15211240     Religious    cardinal                      5933                  3              15994                 9                 14             23.379625                  187576.0  Holy Roman Empire    Europe                      grA        12.482778        12.482778        41.893055        41.893055                                                  D:_diplomat_priest_P:_cardinal_English_cardinal_French_cardinale_arcivescovo_vescovo_Italian_erzbischof_bischof_kardinal_German              AUT

In [28]:
iso_3["map_iso3"].unique()

array(['DEU', 'CZE', 'USA', 'AUT', 'POL', 'RUS', 'UKR', 'BEL', 'ITA',
       'FRA', 'NOR', 'PHL', 'BRA', 'IRL', 'CMR', 'IRN', 'HUN', 'CHN',
       'GBR', 'CAN', nan, 'JPN', 'CHE', 'VEN', 'ECU', 'PRT', 'NLD', 'GRC',
       'IND', 'BGR', 'EGY', 'ARG', 'ROU', 'COL', 'TUV', 'SRB', 'CHL',
       'KOR', 'IDN', 'HRV', 'FIN', 'VNM', 'KWT', 'SGP', 'ESP', 'COG',
       'DNK', 'MYS', 'DMA', 'NGA', 'TUN', 'TUR', 'LAO', 'MEX', 'AUS',
       'PRY', 'SWE', 'ZWE', 'HND', 'GRD', 'SVN', 'PAK', 'GEO', 'KAZ',
       'VUT', 'GHA', 'NZL', 'SYR', 'Serbia and Montenegro', 'JAM', 'BLR',
       'MNE', 'HKG', 'TWN', 'ZAF', 'THA', 'XKX', 'ALB', 'MNG', 'FJI',
       'MLT', 'CUB', 'ISL', 'LBR', 'COM', 'AZE', 'GNB', 'PER', 'CPV',
       'AGO', 'BOL', 'UGA', 'SVK', 'LVA', 'MCO', 'URY', 'BRN', 'BWA',
       'ARM', 'BEN', 'MOZ', 'LTU', 'AND', 'SLV', 'EST', 'KEN', 'LBN',
       'BIH', 'ARE', 'ETH', 'Yugoslavia', 'SUR', 'ISR', 'IRQ', 'MMR',
       'LUX', 'MAR', 'UZB', 'MDA', 'GIN', 'TLS', 'SEN', 'CYP', 'MKD',
       'CIV', 'MUS', 'LBY', 'AFG', 'JOR', 'Korean Peninsula', 'LKA',
       'PSE', 'Tibet', 'GTM', 'ZMB', 'MWI', 'MDV', 'GAB', 'TKM', 'LIE',
       'NER', 'OMN', 'SLE', 'SAU', 'VAT', 'NIC', 'CRI', 'DZA',
       'Overseas Territories of US', 'BLZ', 'TTO', 'MDG', 'BDI', 'PAN',
       'BHR', 'KGZ', 'BFA', 'TGO', 'SWZ', 'YEM', 'GUY', 'HTI', 'PNG',
       'VCT', 'TCD', 'ERI', 'MLI', 'QAT', 'TZA', 'KNA', 'SYC', 'CAF',
       'ATG', 'RWA', 'BGD', 'WSM', 'GMB', 'DJI', 'SDN', 'LCA', 'BRB',
       'KHM', 'STP', 'SOM', 'BTN', 'NPL', 'TJK', 'NAM', 'PRK', 'Scotland',
       'SMR', 'DOM', 'TON', 'MRT', 'BHS', 'SLB', 'GNQ', 'KIR', 'MHL',
       'LSO', 'PLW', 'FSM', 'NRU', 'Kurdistan', "['DNK', 'NOR']",
       'Babylon', 'Judea', 'Transnistria', 'SSD', 'England', 'Wales',
       'Pre-Columbian era', 'British North America', 'MAC', 'Abkhazia',
       'Zanzibar', 'ESH', 'British Empire', 'Urartu',
       'Nagorno-Karabakh Republic'], dtype=object)

#### Citizenship = "Serbia and Montenegro"

> SCG ([source](https://laendercode.net/de/3-letter-code/scg))

In [29]:
iso_3["map_iso3"] = iso_3["map_iso3"].str.replace("Serbia and Montenegro", "SCG")

In [30]:
iso_3.loc[iso_3["citizenship"] == "Serbia and Montenegro"].head()

       wikidata_code   birth  death  gender      occup_l1               name     un_subregion                    bigperiod_birth                    bigperiod_death     curid      occup_l2  occup_l3  avg_no_readers_2015_2018  non_missing_score  total_count_words  no_wiki_editions  no_external_links  notability_index_sum  notability_index_ranking            citizenship un_region group_wikipedia_editions  birth_place_lon  death_place_lon  birth_place_lat  death_place_lat                                                                occup_l3_all citizenship_iso3
1316        Q1010001  1974.0    NaN    Male  Sports/Games       Goran Trobok  Southern Europe  5.Contemporary period 1901-2020AD  5.Contemporary period 1901-2020AD  19821716  Sports/Games  football                     19238                  3               5301                 6                  3             21.772894                  363231.0  Serbia and Montenegro    Europe                      grA        18.413055              NaN        43.856388              NaN  D:_football_P:_football_midfield_English_calciatore_centrocampista_Italian              SCG
75558      Q11714318  1976.0    NaN    Male  Sports/Games          Ivan Ilić  Southern Europe  5.Contemporary period 1901-2020AD  5.Contemporary period 1901-2020AD  38751557  Sports/Games    player                      4612                  3               1603                 2                  1             17.609299                 1142086.5  Serbia and Montenegro    Europe                      grA        19.850000              NaN        43.849998              NaN                              D:_player_P:_volleyball_player_olympic_English              SCG
121484     Q12755307  1980.0    NaN    Male  Sports/Games     Milan Marković  Southern Europe  5.Contemporary period 1901-2020AD  5.Contemporary period 1901-2020AD  43368920  Sports/Games    player                      1579                  3               1574                 2                  1             16.520847                 1379912.0  Serbia and Montenegro    Europe                      grA              NaN              NaN              NaN              NaN                           D:_player_P:_volleyball_player_volleyball_English              SCG
226122      Q1532231  1979.0    NaN  Female  Sports/Games    Silvija Erdelji  Southern Europe  5.Contemporary period 1901-2020AD  5.Contemporary period 1901-2020AD  38002906  Sports/Games    player                      4284                  3               3943                 3                  2             19.128433                  653538.0  Serbia and Montenegro    Europe                      grA        20.090000              NaN        45.931389              NaN                     D:_player_P:_tennis_player_tennis_English_tennis_German              SCG
251703      Q1561321  1962.0    NaN    Male       Culture  Dobrosav Živković  Southern Europe  5.Contemporary period 1901-2020AD  5.Contemporary period 1901-2020AD  31133650  Culture-core    artist                      8116                  3               1849                 3                  5             19.703081                  574112.0  Serbia and Montenegro    Europe                      grA        22.584999              NaN        43.151943              NaN                                            D:_artist_P:_illustrator_English              SCG

#### Citizenship = "Yugoslavia"

> Serbia/SRB as Belgrade was the [capital](https://en.wikipedia.org/wiki/Yugoslavia) of Yugoslavia

In [31]:
iso_3["map_iso3"] = iso_3["map_iso3"].str.replace("Yugoslavia", "SRB")

In [32]:
iso_3.loc[iso_3["citizenship"] == "Yugoslavia"].head()

      wikidata_code   birth   death gender           occup_l1                name    un_subregion                    bigperiod_birth                    bigperiod_death     curid      occup_l2   occup_l3  avg_no_readers_2015_2018  non_missing_score  total_count_words  no_wiki_editions  no_external_links  notability_index_sum  notability_index_ranking citizenship un_region group_wikipedia_editions  birth_place_lon  death_place_lon  birth_place_lat  death_place_lat                                                                                   occup_l3_all citizenship_iso3
7096      Q10285495  1892.0  1981.0   Male            Culture  Francisco Pavlovic  Eastern Europe    4.Mid Modern Period 1751-1900AD  5.Contemporary period 1901-2020AD   1552351  Culture-core    painter                       791                  3               2660                 2                  0             15.663412                 1753001.0  Yugoslavia    Europe                      grB        14.257222       -49.610001        45.675835       -21.802500                                      D:_painter_sculptor_P:_artista_pintura_pintura_Portuguese              SRB
31130      Q1050195  1917.0  1971.0   Male            Culture          Mak Dizdar  Eastern Europe  5.Contemporary period 1901-2020AD  5.Contemporary period 1901-2020AD    462995  Culture-core       poet                    130518                  3               9944                19                 11             26.464762                   68523.0  Yugoslavia    Europe                      grA        17.959167        18.413055        43.083889        43.856388  D:_poet_writer_journalist_P:_ poet_mystic_English_ poeta_Italian_ dichter_christlichen_German              SRB
38520       Q106971  1928.0  2018.0   Male  Discovery/Science    Črtomir Zupančič  Eastern Europe  5.Contemporary period 1901-2020AD  5.Contemporary period 1901-2020AD   3421196      Academia  physicist                      1455                  3               1422                 2                  7             17.724083                  913761.0  Yugoslavia    Europe                      grB        14.516666              NaN        46.049999              NaN                                             D:_physicist_academic_P:_physiker_professor_German              SRB
42905     Q10820385  1930.0     NaN   Male         Leadership       Andrej Marinc  Eastern Europe  5.Contemporary period 1901-2020AD  5.Contemporary period 1901-2020AD  57302819      Politics  political                      3346                  3               1245                 4                  1             17.546995                 1174037.5  Yugoslavia    Europe                      grA        15.264129              NaN        46.229092              NaN                                                   D:_political_politician_P:_communist_English              SRB
47219      Q1091556  1916.0  1993.0   Male            Culture         Esad Mekuli  Eastern Europe  5.Contemporary period 1901-2020AD  5.Contemporary period 1901-2020AD  31617650  Culture-core       poet                     23804                  3               5100                 7                  9             22.996996                  197110.5  Yugoslavia    Europe                      grA        19.945000        21.166666        42.595554        42.666668          D:_linguist_poet_journalist_translator_P:_ poet_scholar_science_English_ poète_French              SRB

#### Citizenship = "Korean Peninsula"

> South Korea/KOR

In [33]:
iso_3["map_iso3"] = iso_3["map_iso3"].str.replace("Korean Peninsula", "KOR")

In [34]:
iso_3.loc[iso_3["citizenship"] == "Korean Peninsula"].head()

      wikidata_code   birth   death  gender           occup_l1                name  un_subregion                      bigperiod_birth                      bigperiod_death     curid      occup_l2    occup_l3  avg_no_readers_2015_2018  non_missing_score  total_count_words  no_wiki_editions  no_external_links  notability_index_sum  notability_index_ranking       citizenship un_region group_wikipedia_editions  birth_place_lon  death_place_lon  birth_place_lat  death_place_lat                                                                                       occup_l3_all citizenship_iso3
21075      Q1036353     NaN     NaN    Male            Culture            An Gyeon  Eastern Asia  2.Post-Classical History 501-1500AD    3.Early Modern Period 1501-1750AD  13629925  Culture-core     painter                     84147                  3               7568                 7                  1             23.044773                  491895.0  Korean Peninsula      Asia                      grA        126.75000       126.750000        36.500000        36.500000  D:_painter_P:_painter_prince_English_peintre_arts_académie_French_pintor_oficial_príncipe_Spanish              KOR
31318      Q1050694  1826.0  1839.0    Male         Leadership   Peter Yu Tae-chol  Eastern Asia      4.Mid Modern Period 1751-1900AD      4.Mid Modern Period 1751-1900AD  17343267      Politics  government                     21293                  3               1694                 5                  1             19.886665                  798922.0  Korean Peninsula      Asia                      grA        127.23333       126.989998        38.316666        37.560001                                                                D:_P:_martyr_son_government_English              KOR
47440     Q10921480  1727.0  1748.0  Female              Other  Princess Hwapyeong  Eastern Asia    3.Early Modern Period 1501-1750AD    3.Early Modern Period 1501-1750AD  54765967        Family    daughter                     28912                  3               6192                 3                  0             20.389620                  870138.0  Korean Peninsula      Asia                      grA              NaN              NaN              NaN              NaN                                                              D:_P:_ daughter_king_daughter_English              KOR
50394       Q110010  1322.0  1371.0    Male  Discovery/Science             Sin Don  Eastern Asia  2.Post-Classical History 501-1500AD  2.Post-Classical History 501-1500AD  33663867      Academia     scholar                     97697                  3               1919                 7                  4             22.738626                  406739.5  Korean Peninsula      Asia                      grA        128.69194              NaN        35.237839              NaN                                                      D:_biographer_P:_monk_scholar_teacher_English              KOR
58348     Q11269988  1565.0  1624.0    Male         Leadership        Jeong Mun-bu  Eastern Asia    3.Early Modern Period 1501-1750AD    3.Early Modern Period 1501-1750AD  35818577      Politics   statesman                     12284                  3               1528                 3                  6             20.080952                  577833.0  Korean Peninsula      Asia                      grA              NaN              NaN              NaN              NaN                                                          D:_P:_statesman_patriot_statesman_English              KOR

#### Citizenship = "Tibet"

> Bhutan/BTN as close neighbor

In [35]:
iso_3["map_iso3"] = iso_3["map_iso3"].str.replace("Tibet", "BTN")

In [36]:
iso_3.loc[iso_3["citizenship"] == "Tibet"].head()

      wikidata_code   birth   death gender    occup_l1                              name  un_subregion                    bigperiod_birth                    bigperiod_death     curid  occup_l2    occup_l3  avg_no_readers_2015_2018  non_missing_score  total_count_words  no_wiki_editions  no_external_links  notability_index_sum  notability_index_ranking citizenship un_region group_wikipedia_editions  birth_place_lon  death_place_lon  birth_place_lat  death_place_lat                                                                           occup_l3_all citizenship_iso3
22619      Q1037372  1907.0  1989.0   Male  Leadership             Tsepon W. D. Shakabpa  Eastern Asia  5.Contemporary period 1901-2020AD  5.Contemporary period 1901-2020AD  17011823  Politics    minister                     12194                  3              11525                 6                  7             22.786739                  219400.0       Tibet      Asia                      grA        91.140816       -97.401947        29.645756        27.742777  D:_diplomat_P:_noble_scholar_minister_English_secrétaire_ministre_gouvernement_French              BTN
47552     Q10924341  1903.0  1986.0   Male  Leadership             Kashopa Chogyal Nyima  Eastern Asia  5.Contemporary period 1901-2020AD  5.Contemporary period 1901-2020AD   7424159  Politics  politician                       874                  3               2529                 2                  0             15.712234                 1746259.0       Tibet      Asia                      grB        89.599564              NaN        28.920259              NaN                                                      D:_politician_P:_politique_French              BTN
48056     Q10943757  1915.0  2001.0   Male  Leadership         Kundeling Woeser Gyaltsen  Eastern Asia  5.Contemporary period 1901-2020AD  5.Contemporary period 1901-2020AD   7675279  Politics  politician                       797                  3               2824                 2                  5             17.522497                  847231.0       Tibet      Asia                      grB              NaN              NaN              NaN              NaN                                 D:_monk_politician_P:_moine_politicien_ministre_French              BTN
53783     Q11111234  1903.0  1950.0   Male  Leadership  Gétak lozang tendzin drakpa tayé  Eastern Asia  5.Contemporary period 1901-2020AD  5.Contemporary period 1901-2020AD   7420805  Politics  politician                      7286                  3               2795                 2                  0             17.928816                 1235052.0       Tibet      Asia                      grB        96.841553        97.179817        30.601669        31.130400                                                      D:_politician_P:_politique_French              BTN
54697     Q11144419  1918.0  2002.0   Male     Missing                     Bomi Rinpoché  Eastern Asia  5.Contemporary period 1901-2020AD  5.Contemporary period 1901-2020AD  11356698   Missing         NaN                      4279                  2               3104                 2                  0             17.214108                 1305588.0       Tibet      Asia                      grB        97.466919        91.140816        28.661276        29.645756                                                                                  D:_P:              BTN

#### Citizenship = "Overseas Territories of US"

> USA as "parent citizenship"

_In retrospect would question this decision to generalize and not impute USA for Overseas Territories._

In [37]:
iso_3["map_iso3"] = iso_3["map_iso3"].str.replace("Overseas Territories of US", "USA")

In [38]:
iso_3.loc[iso_3["citizenship"] == "Overseas Territories of US"].head()

      wikidata_code   birth  death gender      occup_l1             name      un_subregion                    bigperiod_birth                    bigperiod_death     curid      occup_l2  occup_l3  avg_no_readers_2015_2018  non_missing_score  total_count_words  no_wiki_editions  no_external_links  notability_index_sum  notability_index_ranking                 citizenship un_region group_wikipedia_editions  birth_place_lon  death_place_lon  birth_place_lat  death_place_lat                                                                  occup_l3_all citizenship_iso3
28048      Q1043176  1976.0    NaN   Male  Sports/Games  Carlos Quintana  Northern America  5.Contemporary period 1901-2020AD  5.Contemporary period 1901-2020AD  22176267  Sports/Games     boxer                     58519                  3               9705                 9                  2             23.558872                  329251.0  Overseas Territories of US   America                      grA       -67.113335              NaN        18.394722              NaN     D:_boxer_P:_ boxer_boxing_English_boxe_French_pugile_Italian_boxer_German              USA
34014     Q10554766  1991.0    NaN   Male  Sports/Games      Daru Taumua  Northern America  5.Contemporary period 1901-2020AD  5.Contemporary period 1901-2020AD  38770904  Sports/Games  football                       989                  3               2824                 2                  1             16.638754                 1243221.5  Overseas Territories of US   America                      grA              NaN              NaN              NaN              NaN           D:_football_P:_football_English_calciatore_difensore_calcio_Italian              USA
34075     Q10555190  1991.0    NaN   Male  Sports/Games    Casper Kuresa  Northern America  5.Contemporary period 1901-2020AD  5.Contemporary period 1901-2020AD  38827145  Sports/Games  football                      1778                  3               2730                 2                  1             17.189674                 1126732.0  Overseas Territories of US   America                      grA              NaN              NaN              NaN              NaN      D:_football_P:_football_English_calciatore_centrocampista_calcio_Italian              USA
34077     Q10555207  1992.0    NaN   Male  Sports/Games    Charlie Uhrle  Northern America  5.Contemporary period 1901-2020AD  5.Contemporary period 1901-2020AD  38827179  Sports/Games  football                      1067                  3               2794                 2                  1             16.703695                 1229779.0  Overseas Territories of US   America                      grA              NaN              NaN              NaN              NaN        D:_football_P:_football_midfield_English_calciatore_attaccante_Italian              USA
34078     Q10555211  1981.0    NaN   Male  Sports/Games      Diamond Ott  Northern America  5.Contemporary period 1901-2020AD  5.Contemporary period 1901-2020AD  38827196  Sports/Games  football                     89922                  3               2851                 2                  1             21.154278                  729105.0  Overseas Territories of US   America                      grA              NaN              NaN              NaN              NaN  D:_football_P:_football_forward_English_calciatore_attaccante_calcio_Italian              USA

#### Citizenship = "Scotland"

> Great Britain/GBR

In [39]:
iso_3["map_iso3"] = iso_3["map_iso3"].str.replace("Scotland", "GBR")

In [40]:
iso_3.loc[iso_3["citizenship"] == "Scotland"].head()

        wikidata_code   birth   death gender    occup_l1                      name    un_subregion                      bigperiod_birth                      bigperiod_death     curid      occup_l2 occup_l3  avg_no_readers_2015_2018  non_missing_score  total_count_words  no_wiki_editions  no_external_links  notability_index_sum  notability_index_ranking citizenship un_region group_wikipedia_editions  birth_place_lon  death_place_lon  birth_place_lat  death_place_lat                                                                                  occup_l3_all citizenship_iso3
36321        Q1063549  1677.0  1679.0   Male     Culture   Charles Aloysius Ramsay  Western Europe    3.Early Modern Period 1501-1750AD    3.Early Modern Period 1501-1750AD  53314867  Culture-core   writer                      1644                  3               5538                 4                  7             19.715767                  514129.0    Scotland    Europe                      grA              NaN              NaN              NaN              NaN     D:_physician_translator_P:_ writer_translator_English_auteur_French_gelehrte_autor_German              GBR
896372       Q2662862     NaN   620.0   Male  Leadership        Nechtan nepos Uerb  Western Europe  2.Post-Classical History 501-1500AD  2.Post-Classical History 501-1500AD   3851292      Nobility     king                     12480                  3               9689                15                  1             22.076788                  537698.5    Scotland    Europe                      grA              NaN              NaN              NaN              NaN                          D:_P:_ king_English_ fils_French_ re_Italian_ rei_governo_Portuguese              GBR
957620        Q281752     NaN   977.0   Male  Leadership  Amlaíb, King of Scotland  Western Europe  2.Post-Classical History 501-1500AD  2.Post-Classical History 501-1500AD   5617640      Nobility  monarch                     68272                  2              17446                18                  2             24.653606                  287769.0    Scotland    Europe                      grA              NaN              NaN              NaN              NaN                          D:_monarch_P:_ king_sons_grandfather_English_ roi_French_ re_Italian              GBR
2037996       Q711649     NaN  1161.0   Male  Leadership        Fergus of Galloway  Western Europe  2.Post-Classical History 501-1500AD  2.Post-Classical History 501-1500AD   1747517      Nobility     lord                     65710                  3              28530                 6                  5             25.089483                  164902.0    Scotland    Europe                      grA           -3.603              NaN            55.07              NaN  D:_P:_ lord_witness_king_English_ seigneur_royaume_French_signore_Italian_ könig_herr_German              GBR

#### Citizenship = "Kurdistan"

> Turkey/TUR as country with majority of Kurdistan territory

In [41]:
iso_3["map_iso3"] = iso_3["map_iso3"].str.replace("Kurdistan", "TUR")

In [42]:
iso_3.loc[iso_3["citizenship"] == "Kurdistan"].head()

       wikidata_code   birth   death gender           occup_l1                   name                         un_subregion                      bigperiod_birth                      bigperiod_death     curid      occup_l2 occup_l3  avg_no_readers_2015_2018  non_missing_score  total_count_words  no_wiki_editions  no_external_links  notability_index_sum  notability_index_ranking citizenship un_region group_wikipedia_editions  birth_place_lon  death_place_lon  birth_place_lat  death_place_lat                                                                                 occup_l3_all citizenship_iso3
86586      Q11904692     NaN  1153.0   Male         Leadership  Al-Adil ibn al-Sallar  Western Asia (Middle East Caucasus)  2.Post-Classical History 501-1500AD  2.Post-Classical History 501-1500AD  56956930      Military  officer                      1613                  3               6903                 4                  0             17.837622                 1209277.0   Kurdistan      Asia                      grA              NaN        31.235834              NaN        30.044445  D:_officer_P:_commander_vizier_soldier_English_generale_politico_Italian_wesir_kalif_German              TUR
96982      Q12191626     NaN  1260.0   Male         Leadership      Al-Kamil Muhammad  Western Asia (Middle East Caucasus)  2.Post-Classical History 501-1500AD  2.Post-Classical History 501-1500AD  40774906      Nobility     emir                     15422                  3               3461                 6                  0             19.739321                  919298.0   Kurdistan      Asia                      grA              NaN        41.001389              NaN        38.142223                                  D:_P:_ son_emir_uncle_English_prinz_herrscher_sultan_German              TUR
99667      Q12243341  1924.0  2016.0   Male  Discovery/Science          Mustafa Zalmi  Western Asia (Middle East Caucasus)    5.Contemporary period 1901-2020AD    5.Contemporary period 1901-2020AD  51429183      Academia  scholar                     17470                  3               2249                 4                  0             19.096592                 1047576.0   Kurdistan      Asia                      grA        44.000000              NaN        36.183334              NaN                                            D:_scholar_P:_professor_studies_religious_English              TUR
103822      Q1231797  1966.0     NaN   Male            Culture                  Diyar  Western Asia (Middle East Caucasus)    5.Contemporary period 1901-2020AD    5.Contemporary period 1901-2020AD   1880686  Culture-core   singer                     40019                  3               1098                 5                  0             19.391125                 1259830.0   Kurdistan      Asia                      grB        39.605381              NaN        39.019909              NaN                                                                   D:_singer_P:_sänger_German              TUR
115579      Q1259964  1944.0  2009.0   Male            Culture              Ali Latif  Western Asia (Middle East Caucasus)    5.Contemporary period 1901-2020AD    5.Contemporary period 1901-2020AD   5877260  Culture-core   artist                      1917                  3               1504                 2                  3             17.362057                 1007013.0   Kurdistan      Asia                      grB        45.433334              NaN        35.549999              NaN                                                       D:_artist_P:_maler_sport_presse_German              TUR

#### Citizenship = "['DNK', 'NOR']"

> Iceland/ISL as approx. [center of Denmark-Norway kingdom](https://en.wikipedia.org/wiki/Denmark–Norway)

In [43]:
iso_3.loc[iso_3["citizenship"] == "Denmark-Norway"].head()

       wikidata_code   birth   death  gender           occup_l1                name     un_subregion                    bigperiod_birth                    bigperiod_death     curid                              occup_l2        occup_l3  avg_no_readers_2015_2018  non_missing_score  total_count_words  no_wiki_editions  no_external_links  notability_index_sum  notability_index_ranking     citizenship un_region group_wikipedia_editions  birth_place_lon  death_place_lon  birth_place_lat  death_place_lat                                                                              occup_l3_all citizenship_iso3
104510     Q12326077  1760.0  1838.0  Female              Other        Marie Kofoed  Northern Europe    4.Mid Modern Period 1751-1900AD    4.Mid Modern Period 1751-1900AD  53066379                                 Other  philanthropist                      3111                  3               2261                 4                  1             18.070574                  931545.0  Denmark-Norway    Europe                      grA        14.700000        12.593056        55.099998        55.673611  D:_philanthropist_wholesale_P:_business_philanthropist_patriot_English_filantrop_Swedish   ['DNK', 'NOR']
104830     Q12329996  1753.0  1832.0    Male            Culture        Olav Olavsen  Northern Europe    4.Mid Modern Period 1751-1900AD    4.Mid Modern Period 1751-1900AD  48080926                     Culture-periphery       architect                      1212                  3               1596                 4                  4             17.698080                  875431.0  Denmark-Norway    Europe                      grA       -19.445660        11.000000        65.500183        65.000000                                           D:_architect_P:_jurist_architect_jurist_English   ['DNK', 'NOR']
171632       Q139466  1682.0  1744.0    Male            Missing  Zacharias Allewelt  Northern Europe  3.Early Modern Period 1501-1750AD  3.Early Modern Period 1501-1750AD  49691474                               Missing             NaN                      2175                  3               2422                 4                  0             17.088821                 1353109.5  Denmark-Norway    Europe                      grA         5.323333        12.568889        60.392502        55.676109                                                                                     D:_P:   ['DNK', 'NOR']
337220     Q16161158  1660.0  1733.0  Female         Leadership    Ragnhild Abelset  Northern Europe  3.Early Modern Period 1501-1750AD  3.Early Modern Period 1501-1750AD  54870732  Corporate/Executive/Business (large)        merchant                       577                  3               1843                 3                  0             15.270738                 1861207.0  Denmark-Norway    Europe                      grA              NaN              NaN              NaN              NaN                        D:_farmer_business_P:_merchant_English_köpman_make_företag_Swedish   ['DNK', 'NOR']
470540     Q17297409  1679.0  1735.0    Male  Discovery/Science     Andreas Bussæus  Northern Europe  3.Early Modern Period 1501-1750AD  3.Early Modern Period 1501-1750AD   4092624                              Academia       historian                       206                  3                926                 3                  3             14.951650                 1403872.0  Denmark-Norway    Europe                      grB              NaN        12.610600              NaN        56.035999                                                                           D:_historian_P:   ['DNK', 'NOR']

In [44]:
iso_3["map_iso3"] = iso_3["map_iso3"].str.replace("\['DNK', 'NOR'\]", "ISL")

/var/folders/lb/7nh14nb129d59jc654lkpdlm0000gp/T/ipykernel_58108/4146554679.py:1: FutureWarning: The default value of regex will change from True to False in a future version.
  iso_3["citizenship_iso3"] = iso_3["citizenship_iso3"].str.replace("\['DNK', 'NOR'\]", "ISL")

In [47]:
iso_3.loc[iso_3["citizenship"] == "Denmark-Norway"].head()

       wikidata_code   birth   death  gender           occup_l1                name     un_subregion                    bigperiod_birth                    bigperiod_death     curid                              occup_l2        occup_l3  avg_no_readers_2015_2018  non_missing_score  total_count_words  no_wiki_editions  no_external_links  notability_index_sum  notability_index_ranking     citizenship un_region group_wikipedia_editions  birth_place_lon  death_place_lon  birth_place_lat  death_place_lat                                                                              occup_l3_all citizenship_iso3
104510     Q12326077  1760.0  1838.0  Female              Other        Marie Kofoed  Northern Europe    4.Mid Modern Period 1751-1900AD    4.Mid Modern Period 1751-1900AD  53066379                                 Other  philanthropist                      3111                  3               2261                 4                  1             18.070574                  931545.0  Denmark-Norway    Europe                      grA        14.700000        12.593056        55.099998        55.673611  D:_philanthropist_wholesale_P:_business_philanthropist_patriot_English_filantrop_Swedish              ISL
104830     Q12329996  1753.0  1832.0    Male            Culture        Olav Olavsen  Northern Europe    4.Mid Modern Period 1751-1900AD    4.Mid Modern Period 1751-1900AD  48080926                     Culture-periphery       architect                      1212                  3               1596                 4                  4             17.698080                  875431.0  Denmark-Norway    Europe                      grA       -19.445660        11.000000        65.500183        65.000000                                           D:_architect_P:_jurist_architect_jurist_English              ISL
171632       Q139466  1682.0  1744.0    Male            Missing  Zacharias Allewelt  Northern Europe  3.Early Modern Period 1501-1750AD  3.Early Modern Period 1501-1750AD  49691474                               Missing             NaN                      2175                  3               2422                 4                  0             17.088821                 1353109.5  Denmark-Norway    Europe                      grA         5.323333        12.568889        60.392502        55.676109                                                                                     D:_P:              ISL
337220     Q16161158  1660.0  1733.0  Female         Leadership    Ragnhild Abelset  Northern Europe  3.Early Modern Period 1501-1750AD  3.Early Modern Period 1501-1750AD  54870732  Corporate/Executive/Business (large)        merchant                       577                  3               1843                 3                  0             15.270738                 1861207.0  Denmark-Norway    Europe                      grA              NaN              NaN              NaN              NaN                        D:_farmer_business_P:_merchant_English_köpman_make_företag_Swedish              ISL
470540     Q17297409  1679.0  1735.0    Male  Discovery/Science     Andreas Bussæus  Northern Europe  3.Early Modern Period 1501-1750AD  3.Early Modern Period 1501-1750AD   4092624                              Academia       historian                       206                  3                926                 3                  3             14.951650                 1403872.0  Denmark-Norway    Europe                      grB              NaN        12.610600              NaN        56.035999                                                                           D:_historian_P:              ISL

#### Citizenship = "England"/"Wales"

> Great Britain/GBR

In [50]:
iso_3["map_iso3"] = iso_3["map_iso3"].str.replace("England", "GBR")

In [51]:
iso_3.loc[iso_3["citizenship"] == "England"].head()

       wikidata_code   birth   death gender    occup_l1                     name    un_subregion                      bigperiod_birth                      bigperiod_death     curid   occup_l2 occup_l3  avg_no_readers_2015_2018  non_missing_score  total_count_words  no_wiki_editions  no_external_links  notability_index_sum  notability_index_ranking citizenship un_region group_wikipedia_editions  birth_place_lon  death_place_lon  birth_place_lat  death_place_lat                                                                                                                                                             occup_l3_all citizenship_iso3
121982      Q1276952     NaN     NaN   Male       Other                  Eanhere  Western Europe  2.Post-Classical History 501-1500AD  2.Post-Classical History 501-1500AD   2754314     Family  brother                      3057                  3               3913                 3                  3             19.071402                  620167.0     England    Europe                      grA              NaN              NaN              NaN              NaN                                                                                         D:_P:_ ruler_brother_daughter_English_sovrano_Italian_autor_lizenz_medien_German              GBR
126344      Q1285898  1443.0  1460.0   Male       Other  Edmund, Earl of Rutland  Western Europe  2.Post-Classical History 501-1500AD  2.Post-Classical History 501-1500AD   1420053     Family    child                    174238                  3              17433                14                  5             26.334188                  125329.0     England    Europe                      grA         1.102500           -1.492        49.443054        53.680099  D:_judge_P:_child_son_duke_English_ fils_survivant_duc_French_nobile_figlio_duca_Italian_ sohn_überlebende_herzog_German_ hijo_duque_esposa_Spanish_hertig_bror_Swedish              GBR
166570      Q1380878     NaN     NaN   Male       Other                 Vortimer  Western Europe       1.Ancient History Before 500AD       1.Ancient History Before 500AD    985609     Family      son                     44339                  3              10273                12                  1             23.195179                  474268.5     England    Europe                      grA        -0.570000              NaN        52.220001              NaN                                     D:_king_P:_ son_ruler_father_English_ roi_French_principe_signore_rebbe_Italian_ hijo_gobernante_padre_Spanish_ rei_filho_Portuguese              GBR
428416     Q16854008  1578.0  1636.0   Male  Leadership            John Maverick  Western Europe    3.Early Modern Period 1501-1750AD    3.Early Modern Period 1501-1750AD  40062279  Religious    vicar                      6557                  3               1811                 1                  3             18.370527                 1056838.0     England    Europe                      grA              NaN              NaN              NaN              NaN                                                                                                                                        D:_P:_vicar_curate_rector_English              GBR
541018     Q18526281  1794.0  1886.0   Male  Leadership    Abraham Josias Cloëté  Western Europe      4.Mid Modern Period 1751-1900AD      4.Mid Modern Period 1751-1900AD  53471658   Military  officer                      1700                  3               2074                 1                  2             16.870209                 1382751.0     England    Europe                      grA        18.424999           -0.147       -33.924999        51.517700                                                                                                                                      D:_officer_P:_ son_army_son_English              GBR

In [53]:
iso_3["map_iso3"] = iso_3["map_iso3"].str.replace("Wales", "GBR")

In [54]:
iso_3.loc[iso_3["citizenship"] == "Wales"].head()

        wikidata_code  birth  death gender    occup_l1                 name    un_subregion                      bigperiod_birth                      bigperiod_death     curid      occup_l2   occup_l3  avg_no_readers_2015_2018  non_missing_score  total_count_words  no_wiki_editions  no_external_links  notability_index_sum  notability_index_ranking citizenship un_region group_wikipedia_editions  birth_place_lon  death_place_lon  birth_place_lat  death_place_lat                                                                                                                                                                                                        occup_l3_all citizenship_iso3
124008       Q1281127    NaN  904.0   Male  Leadership  Llywarch ap Hyfaidd  Western Europe  2.Post-Classical History 501-1500AD  2.Post-Classical History 501-1500AD   6072315      Military   conquest                      6674                  2               1551                 5                  1             18.351099                  943088.5       Wales    Europe                      grA              NaN              NaN              NaN              NaN                                                                                                                                                                                    D:_P:_ king_conquest_son_English              GBR
853507       Q2519772  488.0  590.0   Male  Leadership       Sawyl Penuchel  Western Europe       1.Ancient History Before 500AD  2.Post-Classical History 501-1500AD   2846431      Nobility  sovereign                     16968                  3               7555                 7                  1             21.442007                  557661.0       Wales    Europe                      grA              NaN              NaN              NaN              NaN                                                                                                                                                           D:_sovereign_P:_ king_English_ roi_French_sovrano_Italian              GBR
1048900      Q3019286  815.0  893.0   Male  Leadership              Hyfaidd  Western Europe  2.Post-Classical History 501-1500AD  2.Post-Classical History 501-1500AD  38582540      Nobility  sovereign                      4894                  3               4761                 4                  1             19.267590                  737834.5       Wales    Europe                      grA              NaN              NaN              NaN              NaN                                                                                                                                             D:_sovereign_P:_ king_English_ roi_règne_royaume_French_sovrano_Italian              GBR
1151847       Q331697  512.0  601.0   Male  Leadership          Saint David  Western Europe  2.Post-Classical History 501-1500AD  2.Post-Classical History 501-1500AD     29007     Religious     priest                    651580                  3              22142                26                 10             29.086170                   40556.0       Wales    Europe                      grA        -4.842222        -5.268611        51.845001        51.882221  D:_priest_P:_bishop_saint_son_English_ saint_église_French_ monaco_vescovo_santo_Italian_königlich_sohn_könig_German_iglesia_santo_patrón_Spanish_igreja_arcebispo_bispo_Portuguese_kyrkoman_biskop_helgon_Swedish              GBR
1216710       Q357835  518.0  599.0   Male     Culture             Taliesin  Western Europe  2.Post-Classical History 501-1500AD  2.Post-Classical History 501-1500AD     86207  Culture-core       poet                    390556                  3              24184                20                 13             28.652405                   30310.0       Wales    Europe                      grA        -3.416667              NaN        52.299999              NaN                         D:_poet_writer_bard_P:_ poet_bard_poet_English_littérature_poète_chanteur_French_ poeta_Italian_ barde_German_ rey_poeta_poeta_Spanish_ poeta_bardo_príncipe_Portuguese_ bard_manus_Swedish              GBR

#### Citizenship = "Babylon"

> Iraq/IRQ, as [Babylon was part of today's Iraq territorry](https://en.wikipedia.org/wiki/Babylon)

In [56]:
iso_3["map_iso3"] = iso_3["map_iso3"].str.replace("Babylon", "IRQ")

In [57]:
iso_3.loc[iso_3["citizenship"] == "Babylon"].head()

       wikidata_code   birth   death gender    occup_l1                name                         un_subregion                 bigperiod_birth                 bigperiod_death     curid  occup_l2   occup_l3  avg_no_readers_2015_2018  non_missing_score  total_count_words  no_wiki_editions  no_external_links  notability_index_sum  notability_index_ranking citizenship un_region group_wikipedia_editions  birth_place_lon  death_place_lon  birth_place_lat  death_place_lat                                                                                                                                                occup_l3_all citizenship_iso3
115282        Q12591  -630.0  -562.0   Male  Leadership   Nebuchadnezzar II  Western Asia (Middle East Caucasus)  1.Ancient History Before 500AD  1.Ancient History Before 500AD     52346  Nobility    monarch                   6353896                  3              39465                75                 18             33.522945                    8132.0     Babylon      Asia                      grA        44.431644        44.431644        32.541782        32.541782                                       D:_monarch_P:_ king_monarch_English_ roi_French_sovrano_Italian_gobernante_Spanish_ filho_rei_Portuguese_kung_Swedish              IRQ
115944        Q12610     NaN -1104.0   Male  Leadership    Nebuchadnezzar I  Western Asia (Middle East Caucasus)  1.Ancient History Before 500AD  1.Ancient History Before 500AD   2555769  Nobility  sovereign                    912649                  3              17945                33                  9             29.348179                   48149.0     Babylon      Asia                      grA              NaN        44.431644              NaN        32.541782  D:_sovereign_P:_ king_monarch_idol_English_ roi_bible_French_ re_Italian_ könig_herrscher_German_ rey_Spanish_ rei_governo_monarca_Portuguese_kung_Swedish              IRQ
121892      Q1276663     NaN     NaN   Male  Leadership       Ea-mukin-zeri  Western Asia (Middle East Caucasus)  1.Ancient History Before 500AD  1.Ancient History Before 500AD  33853655  Nobility    monarch                      6848                  3               5264                10                  1             20.492174                  639817.0     Babylon      Asia                      grA              NaN              NaN              NaN              NaN                                                                                    D:_monarch_P:_ king_English_usurpator_thron_priester_German_ rey_Spanish              IRQ
161715       Q136691 -1157.0 -1157.0   Male  Leadership  Zababa-shuma-iddin  Western Asia (Middle East Caucasus)  1.Ancient History Before 500AD  1.Ancient History Before 500AD  33119222  Nobility       king                     14115                  3               7410                13                  1             21.798203                  548213.5     Babylon      Asia                      grA              NaN              NaN              NaN              NaN                                            D:_king_P:_ king_royal family_English_ roi_règne_royaume_French_herrscher_tochter_sohn_German_ rey_padre_Spanish              IRQ
184871       Q144318     NaN -1132.0   Male  Leadership  Itti-Marduk-balatu  Western Asia (Middle East Caucasus)  1.Ancient History Before 500AD  1.Ancient History Before 500AD  33862265  Nobility  sovereign                     10859                  3               7457                15                  1             21.675896                  563119.0     Babylon      Asia                      grA              NaN              NaN              NaN              NaN                                            D:_sovereign_P:_ king_son_English_ fils_roi_souverain_French_ könig_sohn_thron_German_ rey_hijo_gobernar_Spanish              IRQ

#### Citizenship = "Judea"

> Israel/ISR as close neighbor

In [59]:
iso_3["map_iso3"] = iso_3["map_iso3"].str.replace("Judea", "ISR")

In [60]:
iso_3.loc[iso_3["citizenship"] == "Judea"].head()

       wikidata_code   birth   death  gender           occup_l1              name                         un_subregion                 bigperiod_birth                 bigperiod_death   curid  occup_l2 occup_l3  avg_no_readers_2015_2018  non_missing_score  total_count_words  no_wiki_editions  no_external_links  notability_index_sum  notability_index_ranking citizenship un_region group_wikipedia_editions  birth_place_lon  death_place_lon  birth_place_lat  death_place_lat                                                                                                                                                                                                                                    occup_l3_all citizenship_iso3
118273       Q126689     NaN  -849.0    Male         Leadership       Jehoshaphat  Western Asia (Middle East Caucasus)  1.Ancient History Before 500AD  1.Ancient History Before 500AD   16119  Nobility     king                    698454                  3              20095                36                  5             28.767584                  101776.0       Judea      Asia                      grA              NaN              NaN              NaN              NaN                                                                                        D:_P:_ son_king_son_English_auteur_French_ re_Italian_ sohn_könig_regierung_German_ rey_hija_trono_Spanish_profeta_senhor_filho_Portuguese_bibel_Swedish              ISR
147998       Q134461    37.0   100.0    Male  Discovery/Science          Josephus  Western Asia (Middle East Caucasus)  1.Ancient History Before 500AD  1.Ancient History Before 500AD   16494  Academia  scholar                   3039051                  3              46741                65                 51             33.820354                    1600.5       Judea      Asia                      grA        35.225555        12.482778        31.778889        41.893055  D:_writer_historian_P:_scholar_historian_hagiographer_English_historiographe_French_ scrittore_storico_politico_Italian_schreiber_German_historiador_sacerdote_estadista_Spanish_historiador_sacerdote_imperador_Portuguese_historiker_Swedish              ISR
704546       Q211663  -972.0  -914.0    Male         Leadership          Rehoboam  Western Asia (Middle East Caucasus)  1.Ancient History Before 500AD  1.Ancient History Before 500AD   26022  Nobility  monarch                    937799                  3              22369                45                  8             29.792637                   53071.5       Judea      Asia                      grA        35.225555        35.225555        31.778889        31.778889                                                                             D:_monarch_P:_ king_bible_son_English_ roi_royaume_French_ re_Italian_ könig_mutter_bibel_German_ rey_hijo_reina_Spanish_ rei_Portuguese_ son_kung_regering_Swedish              ISR
896752       Q266591  -140.0   -67.0  Female         Leadership  Salome Alexandra  Western Asia (Middle East Caucasus)  1.Ancient History Before 500AD  1.Ancient History Before 500AD  926035  Nobility    queen                    186125                  3              18545                27                 11             27.779316                   45769.0       Judea      Asia                      grA              NaN              NaN              NaN              NaN                                                   D:_politician_P:_wife of_queen_ruler_English_ reine_French_ regina_moglie di_tenente_Italian_regente_reina_gobernante_Spanish_rainha_esposa_irmã_Portuguese_drottning_regent_gift med_Swedish              ISR
985309        Q28730 -1079.0 -1010.0    Male         Leadership              Saul  Western Asia (Middle East Caucasus)  1.Ancient History Before 500AD  1.Ancient History Before 500AD   28330  Nobility     king                   3343806                  3              44711                56                 10             32.171566                   30681.5       Judea      Asia                      grA        35.231152        35.414444        31.823372        32.433887                                                                                                    D:_politician_judge_P:_ king_English_bible_fils_clan_French_ re_figlio_Italian_ rey_biblia_reina_Spanish_ rei_filho_Portuguese_bibel_Swedish              ISR

#### Citizenship = "Transnistria"

> Part of Moldova/MDA

In [61]:
iso_3["map_iso3"] = iso_3["map_iso3"].str.replace("Transnistria", "MDA")

In [62]:
iso_3.loc[iso_3["citizenship"] == "Transnistria"].head()

       wikidata_code   birth   death gender    occup_l1                name    un_subregion                    bigperiod_birth                    bigperiod_death     curid  occup_l2    occup_l3  avg_no_readers_2015_2018  non_missing_score  total_count_words  no_wiki_editions  no_external_links  notability_index_sum  notability_index_ranking   citizenship un_region group_wikipedia_editions  birth_place_lon  death_place_lon  birth_place_lat  death_place_lat                                                                        occup_l3_all citizenship_iso3
120891     Q12740665  1944.0     NaN   Male  Leadership     Sergey Leontiev  Eastern Europe  5.Contemporary period 1901-2020AD  5.Contemporary period 1901-2020AD   2492773  Politics  politician                      3224                  3               1333                 2                  0             16.374168                 1754283.0  Transnistria    Europe                      grA        29.508888              NaN        47.466389              NaN                                                                    D:_politician_P:              MDA
121040     Q12743640  1942.0     NaN   Male  Leadership     Vladimir Bodnar  Eastern Europe  5.Contemporary period 1901-2020AD  5.Contemporary period 1901-2020AD   4996927  Politics  politician                      3970                  3               1253                 4                  0             17.031059                 1553992.0  Transnistria    Europe                      grA        27.077528              NaN        48.598141              NaN                               D:_politician_P:_politician_deputy_parliament_English              MDA
428665     Q16854444     NaN     NaN   Male  Leadership        Tom Zenovich  Eastern Europe                                NaN                                NaN   4836886  Politics  politician                      1524                  2               1856                 1                  0             15.263898                 2246930.0  Transnistria    Europe                      grA              NaN              NaN              NaN              NaN                                D:_politician_P:_politician_mayor_politician_English              MDA
730071     Q21665054  1887.0  1938.0   Male  Leadership   Vladimir Tsyganko  Eastern Europe    4.Mid Modern Period 1751-1900AD  5.Contemporary period 1901-2020AD  48126401  Politics  politician                      1983                  3               6819                 2                  0             17.520609                 1320645.0  Transnistria    Europe                      grA        28.835278        30.316668        47.022778        59.950001                                   D:_politician_P:_politician_son_architect_English              MDA
955191     Q28120974  1981.0     NaN   Male  Leadership  Aleksandr Martynov  Eastern Europe  5.Contemporary period 1901-2020AD  5.Contemporary period 1901-2020AD  52768086  Politics  politician                     41246                  3               3114                 8                  0             20.868616                  859456.0  Transnistria    Europe                      grA        29.633333              NaN        46.849998              NaN  D:_politician_economist_P:_politician_minister_politician_English_politiker_German              MDA

In [48]:
non_iso_3

["['AUT', 'HUN']",
 'Roman Empire',
 'Holy Roman Empire',
 'Serbia and Montenegro',
 'Yugoslavia',
 'Korean Peninsula',
 'Tibet',
 'Overseas Territories of US',
 'Scotland',
 'Kurdistan',
 "['DNK', 'NOR']",
 'Babylon',
 'Judea',
 'Transnistria',
 'England',
 'Wales',
 'Pre-Columbian era',
 'British North America',
 'Abkhazia',
 'Zanzibar',
 'British Empire',
 'Urartu',
 'Nagorno-Karabakh Republic']

In [70]:
# check remaining non-ISO3 values for number of rows (i.e. relevance to impute)

iso_3.loc[iso_3["citizenship"] == "Nagorno-Karabakh Republic"]

        wikidata_code   birth  death gender    occup_l1                 name                         un_subregion                    bigperiod_birth                    bigperiod_death     curid  occup_l2    occup_l3  avg_no_readers_2015_2018  non_missing_score  total_count_words  no_wiki_editions  no_external_links  notability_index_sum  notability_index_ranking                citizenship un_region group_wikipedia_editions  birth_place_lon  death_place_lon  birth_place_lat  death_place_lat                                                  occup_l3_all           citizenship_iso3
1320590      Q4076418  1959.0    NaN   Male  Leadership    Vitaly Balasanyan  Western Asia (Middle East Caucasus)  5.Contemporary period 1901-2020AD  5.Contemporary period 1901-2020AD  50546617  Politics  politician                     34032                  3               4009                 6                  0             20.677631                  842681.0  Nagorno-Karabakh Republic      Asia                      grA        46.832779              NaN        39.936668              NaN           D:_politician_P:_secretary_English_politico_Italian  Nagorno-Karabakh Republic
1434381     Q47493489  1978.0    NaN   Male  Leadership  Grigory Martirosyan  Western Asia (Middle East Caucasus)  5.Contemporary period 1901-2020AD  5.Contemporary period 1901-2020AD  58019071  Politics  politician                      1081                  3               1395                 3                  0             15.616996                 1893957.0  Nagorno-Karabakh Republic      Asia                      grA        46.751945              NaN        39.815277              NaN        D:_economist_P:_politician_minister_politician_English  Nagorno-Karabakh Republic
1558834      Q5159740  1982.0    NaN   Male  Leadership     Arsen Miqajeljan  Western Asia (Middle East Caucasus)  5.Contemporary period 1901-2020AD  5.Contemporary period 1901-2020AD   7553484  Politics  politician                      1277                  3               1197                 2                  0             15.342418                 2067498.0  Nagorno-Karabakh Republic      Asia                      grB        46.751945              NaN        39.815277              NaN  D:_bank_economist_P:_politiker_parlament_abgeordneter_German  Nagorno-Karabakh Republic

##### --> Remaining non-ISO3 codes stay as is, as only very few records exist for those territories

## Write into new File with cleaned ISO 3 Codes

In [73]:
# iso_3.to_csv("../data/notable_people_cross-verified/wiki_notable_people_cleaned_iso.csv", index=False)

In [74]:
iso_3.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 2291817 entries, 0 to 2291816
Data columns (total 28 columns):
 #   Column                    Dtype
---  ------                    -----
 0   wikidata_code             object
 1   birth                     float64
 2   death                     float64
 3   gender                    object
 4   occup_l1                  object
 5   name                      object
 6   un_subregion              object
 7   bigperiod_birth           object
 8   bigperiod_death           object
 9   curid                     int64
 10  occup_l2                  object
 11  occup_l3                  object
 12  avg_no_readers_2015_2018  int64
 13  non_missing_score         int64
 14  total_count_words         int64
 15  no_wiki_editions          int64
 16  no_external_links         int64
 17  notability_index_sum      float64
 18  notability_index_ranking  float64
 19  citizenship               object
 20  un_region                 object
 21  group_wikipedia_editions  object
 22  birth_place_lon           float64
 23  death_place_lon           float64
 24  birth_place_lat           float64
 25  death_place_lat           float64
 26  occup_l3_all              object
 27  map_iso3                  object
dtypes: float64(8), int64(6), object(14)
memory usage: 507.1+ MB

In [75]:
iso_3["map_iso3"].unique()

array(['DEU', 'CZE', 'USA', 'AUT', 'POL', 'RUS', 'UKR', 'BEL', 'ITA',
       'FRA', 'NOR', 'PHL', 'BRA', 'IRL', 'CMR', 'IRN', 'HUN', 'CHN',
       'GBR', 'CAN', nan, 'JPN', 'CHE', 'VEN', 'ECU', 'PRT', 'NLD', 'GRC',
       'IND', 'BGR', 'EGY', 'ARG', 'ROU', 'COL', 'TUV', 'SRB', 'CHL',
       'KOR', 'IDN', 'HRV', 'FIN', 'VNM', 'KWT', 'SGP', 'ESP', 'COG',
       'DNK', 'MYS', 'DMA', 'NGA', 'TUN', 'TUR', 'LAO', 'MEX', 'AUS',
       'PRY', 'SWE', 'ZWE', 'HND', 'GRD', 'SVN', 'PAK', 'GEO', 'KAZ',
       'VUT', 'GHA', 'NZL', 'SYR', 'SCG', 'JAM', 'BLR', 'MNE', 'HKG',
       'TWN', 'ZAF', 'THA', 'XKX', 'ALB', 'MNG', 'FJI', 'MLT', 'CUB',
       'ISL', 'LBR', 'COM', 'AZE', 'GNB', 'PER', 'CPV', 'AGO', 'BOL',
       'UGA', 'SVK', 'LVA', 'MCO', 'URY', 'BRN', 'BWA', 'ARM', 'BEN',
       'MOZ', 'LTU', 'AND', 'SLV', 'EST', 'KEN', 'LBN', 'BIH', 'ARE',
       'ETH', 'SUR', 'ISR', 'IRQ', 'MMR', 'LUX', 'MAR', 'UZB', 'MDA',
       'GIN', 'TLS', 'SEN', 'CYP', 'MKD', 'CIV', 'MUS', 'LBY', 'AFG',
       'JOR', 'LKA', 'PSE', 'BTN', 'GTM', 'ZMB', 'MWI', 'MDV', 'GAB',
       'TKM', 'LIE', 'NER', 'OMN', 'SLE', 'SAU', 'VAT', 'NIC', 'CRI',
       'DZA', 'BLZ', 'TTO', 'MDG', 'BDI', 'PAN', 'BHR', 'KGZ', 'BFA',
       'TGO', 'SWZ', 'YEM', 'GUY', 'HTI', 'PNG', 'VCT', 'TCD', 'ERI',
       'MLI', 'QAT', 'TZA', 'KNA', 'SYC', 'CAF', 'ATG', 'RWA', 'BGD',
       'WSM', 'GMB', 'DJI', 'SDN', 'LCA', 'BRB', 'KHM', 'STP', 'SOM',
       'NPL', 'TJK', 'NAM', 'PRK', 'SMR', 'DOM', 'TON', 'MRT', 'BHS',
       'SLB', 'GNQ', 'KIR', 'MHL', 'LSO', 'PLW', 'FSM', 'NRU', 'SSD',
       'Pre-Columbian era', 'British North America', 'MAC', 'Abkhazia',
       'Zanzibar', 'ESH', 'British Empire', 'Urartu',
       'Nagorno-Karabakh Republic'], dtype=object)